language: android
jdk: oraclejdk8

android:
  components:
    - tools
  licenses:
    - android-sdk-license-.+

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  # Suppress output to keep log under Travis limit
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "tools" > /dev/null
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platform-tools" > /dev/null
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;26.0.2" > /dev/null
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platforms;android-26" > /dev/null

script: ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

notifications:
  email: false
